---
- hosts: all
  sudo: true
  vars:
    web_server: nginxphp
    servername: default 192.168.33.90
    timezone: UTC
  vars_files:
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
    - vars/mysql.yml
  roles:
    - init
    - php5-cli
    - nginx
    - php5-fpm
    - composer
    - phpcommon
    - app
    - mysql
